spring.application.name=DoctorService

server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/microservicework
spring.datasource.username=root
spring.datasource.password=Govind

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true